openapi: 3.1.0
info:
  version: 0.0.1
  title: Leagueify Statistics API
  summary: Open Source Sporting League Platform.
  description: '
    The Leagueify statistics is responsible for managing user
    authentication, authorization, and profiles.
    '
  license:
    name: MIT
    url: https://raw.githubusercontent.com/Leagueify/statistics/main/LICENSE
  contact:
    name: Leagueify Support
    url: https://github.com/Leagueify/statistics/issues

servers:
  - url: http://localhost:6505/statistics
    description: DIRECT -- Local Docker Development
  - url: http://localhost/statistics
    description: PROXY -- Local Docker Development
  - url: http://localhost/api/statistics
    description: PREFIX PROXY -- Local Docker Development

paths:
  /healthz:
    get:
      tags:
      - Health Check
      summary: Statistics Service Health Check
      description: '
        Check the health status of the Leagueify Statistics service. This
        endpoint should return the service name and a status of ok.
        '
      responses:
        200:
          description: Health Check Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    description: Service Name
                    type: string
                    example: statistics
                  status:
                    description: Server HTTP Status
                    type: string
                    example: ok
